version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: parking-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: parking_system
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - parking-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parking-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: parking_system
      DB_USER: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: ${JWT_SECRET:-parking_system_secret_key}
      JWT_EXPIRES_IN: 24h
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - parking-network
    command: npm run dev

networks:
  parking-network:
    driver: bridge

volumes:
  postgres_data:
